# example of a machine specific settings
windows:
  mainwindow:
    provider: custom_probebasic:CustomProbeBasic
    kwargs:
      confirm_exit: false

data_plugins:
  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable
    kwargs:
      columns: TZDR

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable
    kwargs:
      columns: "XYZACR"

settings:

  # VTK backplot view settings

  backplot.show-grid:
    default_value: false

  backplot.show-program-bounds:
    default_value: false

  backplot.show-program-labels:
    default_value: false

  backplot.show-program-ticks:
    default_value: false

  backplot.show-machine-bounds:
    default_value: false

  backplot.show-machine-labels:
    default_value: false

  backplot.show-machine-ticks:
    default_value: false

  backplot.perspective-view:
    default_value: false

  backplot.multitool-colors:
    default_value: true

  backplot.show-points-surface:
    default_value: true

  backplot.surface-map-transparency:
    default_value: 50
    persistent: true
    min_value: 0
    max_value: 100

  backplot.show-machine-model:
    default_value: false
